GET http://localhost:8080/todos

###

PATCH  http://localhost:8080/todos/edit/64d7143f48f0fed3c8f61e38
content-type: application/json

{
    "content": "This has been updated"
}

###

POST http://localhost:8080/todos/new
content-type: application/json

{
    "content": "Test2"
}

###
DELETE http://localhost:8080/todos/delete/64d7143f48f0fed3c8f61e38

###

DELETE http://localhost:8080/todos/delete/